### PR TITLE
API Updates

### PR DESCRIPTION
**Pull request by deanpcmad**

### CODE REVIEW

**Comment by harrison-broadbent** [comment]
You have no idea how keen I am for this + the subsequent `pay` gem integration!

I don't normally do too much OS stuff, but sing out if you need a hand 💪

**Comment by deanpcmad** [comment]
Thanks @harrison-broadbent. This reminds me, I need to work on this again. I think I need to contact the LemonSqueezy guys as a couple of the API calls are off from what their docs say. Will try and work on this over the weekend

**Comment by harrison-hd** [comment]
> Thanks @harrison-broadbent. This reminds me, I need to work on this again. I think I need to contact the LemonSqueezy guys as a couple of the API calls are off from what their docs say. Will try and work on this over the weekend

(replying from my work acc 😅 ) No stress! Annoying that they're off, I've found the team to be relatively responsive though + they're super active on Twitter, so hopefully it should be easy to get some more info.

**Comment by harrison-broadbent** [comment]
🙏

**Comment by deanpcmad** [comment]
v1.0 is now released 🎉

**Comment by harrison-broadbent** [comment]
sickkkkkk nice one dude! 🚀

**Pull request merged**
